### ISSUE TITLE
Have you ever tried on MovingMNIST?

### ISSUE THREAD

**Issue by GajuuzZ** [AILAB-CEFET-RJ/stconvs2s#3]
Many related works about spatial-temporal use MovingMNIST dataset with 10 input and 10 output frames to test their model.

**Comment by rafaela00castro** [comment]
No, we haven't. In this work, we focus on the weather forecasting problem. But the STConvS2S architecture 
 (R and C) isn't limited to this domain. So we encourage the community to try it in other domains.
